"""Local owner voice verification for MERRICK

Only speaker embeddings are retained.  Raw microphone samples are decoded in
memory, embedded locally, and immediately discarded.  This is deliberately a
speaker-verification convenience and privacy gate, not anti-spoofing or a
substitute for macOS authentication.
"""

from __future__ import annotations

import base64
import binascii
import json
import math
import os
import tempfile
import wave
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SAMPLE_RATE = 16_000
MINIMUM_SPEECH_SECONDS = 1.35
FAST_MINIMUM_SPEECH_SECONDS = 0.55
OWNER_SIMILARITY_THRESHOLD = 0.78
FAST_OWNER_SIMILARITY_THRESHOLD = 0.60
MAX_ANCHOR_EMBEDDINGS = 10
MAX_ADAPTIVE_EMBEDDINGS = 10
AUTO_REFINEMENT_DUPLICATE_SIMILARITY = 0.985
# Live samples are generated by the native host at roughly 144 KB.  Manual
# enrollment may deliberately contain a longer local recording, so permit a
# bounded 4 MB WAV while still rejecting oversized WebSocket payloads.
MAX_SAMPLE_BYTES = 4_000_000
PROFILE_VERSION = 2


@dataclass(frozen=True)
class VoiceVerdict:
    status: str
    score: float | None = None

    @property
    def is_owner(self) -> bool:
        return self.status == "owner"


class OwnerVoiceVerifier:
    """One local voiceprint profile with an intentionally conservative gate."""

    def __init__(self, state_dir: Path) -> None:
        self.state_dir = state_dir
        self.profile_path = state_dir / "identity" / "owner-voiceprint.json"
        self._encoder: Any | None = None
        self._numpy: Any | None = None
        self._preprocess_wav: Any | None = None

    def profile_exists(self) -> bool:
        return self._load_embeddings() is not None

    def profile_embedding_count(self) -> int:
        """Return only a count; management UI never reads raw vectors."""
        return len(self._load_embeddings() or [])

    def prewarm(self) -> None:
        """Load the local encoder once, outside of the interactive turn path."""
        self._load_encoder()

    def enroll(self, encoded_wav: str) -> int:
        embedding = self._embed(encoded_wav)
        payload = self._load_profile() or self._empty_profile()
        anchors = self._profile_embeddings(payload, "anchors")
        anchors.append([float(value) for value in embedding])
        # Manual enrollment is the stable user-approved baseline. Adaptive
        # learning never evicts these anchor vectors.
        payload["version"] = PROFILE_VERSION
        payload["created_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        payload["anchors"] = anchors[-MAX_ANCHOR_EMBEDDINGS:]
        payload["adaptive_embeddings"] = self._profile_embeddings(payload, "adaptive_embeddings")
        self._write_profile(payload)
        return len(payload["anchors"]) + len(payload["adaptive_embeddings"])

    def discard_last_enrollment(self) -> int:
        """Remove only the most recently added local voice embedding."""
        payload = self._load_profile()
        anchors = self._profile_embeddings(payload, "anchors") if payload else []
        if not anchors:
            return 0
        payload["anchors"] = anchors[:-1]
        payload["created_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        self._write_profile(payload)
        return len(payload["anchors"]) + len(self._profile_embeddings(payload, "adaptive_embeddings"))

    def refine_from_verified_sample(self, encoded_wav: str) -> tuple[int, bool]:
        """Add one locally verified, meaningfully new acoustic condition.

        Callers must apply their own high-confidence owner check before using
        this method. Raw audio is decoded only to create the local embedding
        and is never written to disk.
        """
        candidate = self._embed(encoded_wav)
        payload = self._load_profile() or self._empty_profile()
        anchors = self._profile_embeddings(payload, "anchors")
        adaptive = self._profile_embeddings(payload, "adaptive_embeddings")
        embeddings = anchors + adaptive
        if any(
            self._cosine(candidate, reference) >= AUTO_REFINEMENT_DUPLICATE_SIMILARITY
            for reference in embeddings
        ):
            return (len(embeddings), False)
        adaptive.append(candidate)
        if len(adaptive) > MAX_ADAPTIVE_EMBEDDINGS:
            # Adaptive entries compete only with each other. User-enrolled
            # anchors stay intact while the learned pool retains diversity.
            candidates = anchors + adaptive
            redundancy = [
                max(
                    self._cosine(adaptive_embedding, other)
                    for other_index, other in enumerate(candidates)
                    if other is not adaptive_embedding
                )
                for adaptive_embedding in adaptive
            ]
            adaptive.pop(max(range(len(adaptive)), key=lambda index: redundancy[index]))
        payload["version"] = PROFILE_VERSION
        payload["created_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        payload["anchors"] = [[float(value) for value in embedding] for embedding in anchors]
        payload["adaptive_embeddings"] = [
            [float(value) for value in embedding] for embedding in adaptive
        ]
        self._write_profile(payload)
        return (len(anchors) + len(adaptive), True)

    def verify(self, encoded_wav: str, *, fast: bool = False) -> VoiceVerdict:
        embeddings = self._load_embeddings()
        if not embeddings:
            return VoiceVerdict("unregistered")
        candidate = self._embed(
            encoded_wav,
            minimum_speech_seconds=(
                FAST_MINIMUM_SPEECH_SECONDS if fast else MINIMUM_SPEECH_SECONDS
            ),
        )
        score = max(self._cosine(candidate, reference) for reference in embeddings)
        threshold = FAST_OWNER_SIMILARITY_THRESHOLD if fast else OWNER_SIMILARITY_THRESHOLD
        return VoiceVerdict("owner" if score >= threshold else "guest", score)

    def _load_encoder(self) -> None:
        if self._encoder is not None:
            return
        # Kept lazy so importing the FastAPI app remains cheap; app lifespan
        # calls prewarm in a background task after /health is available.
        import numpy as np
        import torch
        from resemblyzer import VoiceEncoder, preprocess_wav

        self._numpy = np
        self._preprocess_wav = preprocess_wav
        device = "mps" if torch.backends.mps.is_available() else "cpu"
        self._encoder = VoiceEncoder(device=device)

    def _embed(
        self, encoded_wav: str, *, minimum_speech_seconds: float = MINIMUM_SPEECH_SECONDS
    ) -> list[float]:
        self._load_encoder()
        assert self._encoder is not None
        assert self._numpy is not None
        assert self._preprocess_wav is not None
        raw = self._decode_wav(encoded_wav)
        pcm, source_rate = self._read_pcm(raw)
        duration = len(pcm) / float(source_rate)
        if duration < minimum_speech_seconds:
            raise ValueError("Voice sample was too short.")
        # Resemblyzer's local preprocessor explicitly normalizes speech volume
        # and removes long non-speech spans with WebRTC VAD before embedding.
        prepared = self._preprocess_wav(pcm, source_sr=source_rate)
        if len(prepared) < int(SAMPLE_RATE * minimum_speech_seconds):
            raise ValueError("Voice sample did not contain enough speech.")
        embedding = self._encoder.embed_utterance(prepared)
        return [float(value) for value in embedding.tolist()]

    @staticmethod
    def _decode_wav(encoded_wav: str) -> bytes:
        if not isinstance(encoded_wav, str) or len(encoded_wav) > MAX_SAMPLE_BYTES * 2:
            raise ValueError("Voice sample payload was invalid.")
        try:
            raw = base64.b64decode(encoded_wav, validate=True)
        except (binascii.Error, ValueError, TypeError) as exc:
            raise ValueError("Voice sample payload was invalid.") from exc
        if not raw or len(raw) > MAX_SAMPLE_BYTES:
            raise ValueError("Voice sample payload was invalid.")
        return raw

    def _read_pcm(self, raw: bytes) -> tuple[Any, int]:
        assert self._numpy is not None
        with tempfile.NamedTemporaryFile(suffix=".wav") as handle:
            handle.write(raw)
            handle.flush()
            with wave.open(handle.name, "rb") as wav:
                if wav.getnchannels() != 1 or wav.getsampwidth() != 2:
                    raise ValueError("Voice sample format was invalid.")
                rate = wav.getframerate()
                if rate < 8_000 or rate > 48_000:
                    raise ValueError("Voice sample format was invalid.")
                frames = wav.readframes(wav.getnframes())
        return self._numpy.frombuffer(frames, dtype="<i2").astype(self._numpy.float32) / 32768.0, rate

    def _load_profile(self) -> dict[str, Any] | None:
        try:
            payload = json.loads(self.profile_path.read_text(encoding="utf-8"))
        except (OSError, TypeError, ValueError):
            return None
        if not isinstance(payload, dict):
            return None
        # Version 1 contained only manually collected embeddings. Preserve all
        # of them as non-evictable anchors when moving to the two-pool profile.
        if payload.get("version") == 1 and isinstance(payload.get("embeddings"), list):
            return {
                "version": PROFILE_VERSION,
                "created_at": payload.get("created_at", ""),
                "anchors": payload["embeddings"][-MAX_ANCHOR_EMBEDDINGS:],
                "adaptive_embeddings": [],
            }
        return payload

    @staticmethod
    def _empty_profile() -> dict[str, Any]:
        return {"version": PROFILE_VERSION, "anchors": [], "adaptive_embeddings": []}

    @staticmethod
    def _profile_embeddings(payload: dict[str, Any] | None, key: str) -> list[list[float]]:
        raw = payload.get(key) if payload else None
        if not isinstance(raw, list):
            return []
        embeddings: list[list[float]] = []
        for item in raw:
            if not isinstance(item, list) or len(item) != 256:
                continue
            try:
                values = [float(value) for value in item]
            except (TypeError, ValueError):
                continue
            if all(math.isfinite(value) for value in values):
                embeddings.append(values)
        return embeddings

    def _load_embeddings(self) -> list[list[float]] | None:
        payload = self._load_profile()
        if not payload or payload.get("version") != PROFILE_VERSION:
            return None
        anchors = self._profile_embeddings(payload, "anchors")[-MAX_ANCHOR_EMBEDDINGS:]
        adaptive = self._profile_embeddings(payload, "adaptive_embeddings")[-MAX_ADAPTIVE_EMBEDDINGS:]
        return anchors + adaptive or None

    def _write_profile(self, payload: dict[str, Any]) -> None:
        self.profile_path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        fd, temporary_name = tempfile.mkstemp(prefix="owner-voiceprint-", dir=self.profile_path.parent)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                json.dump(payload, handle, ensure_ascii=False, separators=(",", ":"))
                handle.write("\n")
            os.chmod(temporary_name, 0o600)
            os.replace(temporary_name, self.profile_path)
            os.chmod(self.profile_path, 0o600)
        finally:
            if os.path.exists(temporary_name):
                os.unlink(temporary_name)

    @staticmethod
    def _cosine(left: list[float], right: list[float]) -> float:
        numerator = sum(a * b for a, b in zip(left, right))
        left_norm = math.sqrt(sum(value * value for value in left))
        right_norm = math.sqrt(sum(value * value for value in right))
        return numerator / max(left_norm * right_norm, 1e-12)
