# Generated by scripts/generate-runtime-contract.py. Do not edit.
# contract-sha256: 14aaefe61bc21c90f1fb770a991367466656817b5d413ab95e01f180aa45cfc8
JARVIS_DEFAULT_PROVIDER=codex
JARVIS_DEFAULT_MODEL='gpt-5.5'
JARVIS_DEFAULT_PROBE_ROUTE='openai'
JARVIS_DEFAULT_PROBE_PROFILE_ID='openai:jarvis'
JARVIS_BACKEND_HOST='127.0.0.1'
JARVIS_BACKEND_PORT=8765
OPENCLAW_DEFAULT_HOST='127.0.0.1'
OPENCLAW_DEFAULT_PORT=18789

merrick_apply_provider_contract() {
  JARVIS_CONVERSATION_MODEL=""
  case "$JARVIS_SELECTED_PROVIDER" in
  codex)
    JARVIS_MAIN_MODEL="openai/$JARVIS_SELECTED_MODEL"
    JARVIS_OPENAI_RUNTIME='codex'
    JARVIS_ANTHROPIC_RUNTIME='openclaw'
    JARVIS_CONVERSATION_MODEL='openai/gpt-5.4-mini'
    : "${JARVIS_SELECTED_BASE_URL:=https://api.openai.com/v1}"
    ;;
  claude-code)
    JARVIS_MAIN_MODEL="anthropic/$JARVIS_SELECTED_MODEL"
    JARVIS_OPENAI_RUNTIME='openclaw'
    JARVIS_ANTHROPIC_RUNTIME='claude-cli'
    : "${JARVIS_SELECTED_BASE_URL:=https://api.anthropic.com}"
    ;;
  openai)
    JARVIS_MAIN_MODEL="jarvis-openai-api/$JARVIS_SELECTED_MODEL"
    JARVIS_OPENAI_RUNTIME='openclaw'
    JARVIS_ANTHROPIC_RUNTIME='openclaw'
    : "${JARVIS_SELECTED_BASE_URL:=https://api.openai.com/v1}"
    ;;
  anthropic)
    JARVIS_MAIN_MODEL="jarvis-anthropic-api/$JARVIS_SELECTED_MODEL"
    JARVIS_OPENAI_RUNTIME='openclaw'
    JARVIS_ANTHROPIC_RUNTIME='openclaw'
    : "${JARVIS_SELECTED_BASE_URL:=https://api.anthropic.com}"
    ;;
  gemini)
    JARVIS_MAIN_MODEL="jarvis-google-api/$JARVIS_SELECTED_MODEL"
    JARVIS_OPENAI_RUNTIME='openclaw'
    JARVIS_ANTHROPIC_RUNTIME='openclaw'
    : "${JARVIS_SELECTED_BASE_URL:=https://generativelanguage.googleapis.com}"
    ;;
  kimi)
    JARVIS_MAIN_MODEL="jarvis-moonshot-api/$JARVIS_SELECTED_MODEL"
    JARVIS_OPENAI_RUNTIME='openclaw'
    JARVIS_ANTHROPIC_RUNTIME='openclaw'
    : "${JARVIS_SELECTED_BASE_URL:=https://api.moonshot.ai/v1}"
    ;;
  deepseek)
    JARVIS_MAIN_MODEL="jarvis-compatible/$JARVIS_SELECTED_MODEL"
    JARVIS_OPENAI_RUNTIME='openclaw'
    JARVIS_ANTHROPIC_RUNTIME='openclaw'
    : "${JARVIS_SELECTED_BASE_URL:=https://api.deepseek.com}"
    ;;
  custom)
    JARVIS_MAIN_MODEL="jarvis-compatible/$JARVIS_SELECTED_MODEL"
    JARVIS_OPENAI_RUNTIME='openclaw'
    JARVIS_ANTHROPIC_RUNTIME='openclaw'
    if [ -z "$JARVIS_SELECTED_BASE_URL" ]; then
      echo "A custom provider needs an HTTPS base URL." >&2
      return 1
    fi
    ;;
  *)
    echo "Unsupported MERRICK provider selection." >&2
    return 1
    ;;
  esac
  JARVIS_CONVERSATION_MODEL=${JARVIS_CONVERSATION_MODEL:-$JARVIS_MAIN_MODEL}
}
