// Generated by scripts/generate-runtime-contract.py. Do not edit.
// contract-sha256: 14aaefe61bc21c90f1fb770a991367466656817b5d413ab95e01f180aa45cfc8
import Foundation

enum ProviderConnectionStage: String, Codable {
    case notConfigured = "not_configured"
    case credentialStored = "credential_stored"
    case validating = "validating"
    case ready = "ready"
    case failed = "failed"
}

struct ProviderContractSpec {
    let id: String
    let title: String
    let detail: String
    let defaultModel: String
    let authMode: String
    let profileAuthMode: String
    let runtimeRoute: String
    let probeRoute: String
    let probeProfileID: String?
    let defaultBaseURL: String
    let baseURLRequired: Bool
    let conversationModel: String?
    let openAIRuntime: String
    let anthropicRuntime: String
    let credentialEnvironmentNames: [String]
}

struct ConnectionFailureContractSpec {
    let code: String
    let retryable: Bool
    let reconnectRequired: Bool
    let messageEnglish: String
    let messageChinese: String
    let shortEnglish: String
    let shortChinese: String
}

struct FailureMatcherContractSpec {
    let runtimeCode: String
    let probeCode: String
    let pattern: String
}

enum RuntimeContract {
    static let digest = "14aaefe61bc21c90f1fb770a991367466656817b5d413ab95e01f180aa45cfc8"
    static let backendHost = "127.0.0.1"
    static let backendPort = 8765
    static let backendHealthPath = "/health"
    static let backendWebSocketPath = "/ws"
    static let openClawHost = "127.0.0.1"
    static let openClawDefaultPort = 18789

    static let providers: [String: ProviderContractSpec] = [
        "codex": ProviderContractSpec(
            id: "codex", title: "Codex subscription", detail: "Use a MERRICK-owned ChatGPT / Codex sign-in. A browser window may open to finish authentication.",
            defaultModel: "gpt-5.5", authMode: "cli",
            profileAuthMode: "jarvis-oauth", runtimeRoute: "openai",
            probeRoute: "openai", probeProfileID: "openai:jarvis",
            defaultBaseURL: "https://api.openai.com/v1", baseURLRequired: false,
            conversationModel: "openai/gpt-5.4-mini",
            openAIRuntime: "codex", anthropicRuntime: "openclaw",
            credentialEnvironmentNames: []
        ),
        "claude-code": ProviderContractSpec(
            id: "claude-code", title: "Claude Code", detail: "Use the installed Claude Code CLI and its local login. MERRICK never receives the subscription password or token.",
            defaultModel: "claude-sonnet-5", authMode: "cli",
            profileAuthMode: "cli", runtimeRoute: "anthropic",
            probeRoute: "claude-cli", probeProfileID: nil,
            defaultBaseURL: "https://api.anthropic.com", baseURLRequired: false,
            conversationModel: nil,
            openAIRuntime: "openclaw", anthropicRuntime: "claude-cli",
            credentialEnvironmentNames: []
        ),
        "openai": ProviderContractSpec(
            id: "openai", title: "OpenAI API", detail: "Connect a paid OpenAI Platform API key. This is separate from a ChatGPT subscription.",
            defaultModel: "gpt-5.5", authMode: "api",
            profileAuthMode: "api", runtimeRoute: "jarvis-openai-api",
            probeRoute: "jarvis-openai-api", probeProfileID: nil,
            defaultBaseURL: "https://api.openai.com/v1", baseURLRequired: false,
            conversationModel: nil,
            openAIRuntime: "openclaw", anthropicRuntime: "openclaw",
            credentialEnvironmentNames: ["OPENAI_API_KEY"]
        ),
        "anthropic": ProviderContractSpec(
            id: "anthropic", title: "Anthropic API", detail: "Connect an Anthropic Console API key for direct Claude API access.",
            defaultModel: "claude-sonnet-5", authMode: "api",
            profileAuthMode: "api", runtimeRoute: "jarvis-anthropic-api",
            probeRoute: "jarvis-anthropic-api", probeProfileID: nil,
            defaultBaseURL: "https://api.anthropic.com", baseURLRequired: false,
            conversationModel: nil,
            openAIRuntime: "openclaw", anthropicRuntime: "openclaw",
            credentialEnvironmentNames: ["ANTHROPIC_API_KEY"]
        ),
        "gemini": ProviderContractSpec(
            id: "gemini", title: "Google Gemini", detail: "Connect a Google AI Studio Gemini API key.",
            defaultModel: "gemini-3.1-pro-preview", authMode: "api",
            profileAuthMode: "api", runtimeRoute: "jarvis-google-api",
            probeRoute: "jarvis-google-api", probeProfileID: nil,
            defaultBaseURL: "https://generativelanguage.googleapis.com", baseURLRequired: false,
            conversationModel: nil,
            openAIRuntime: "openclaw", anthropicRuntime: "openclaw",
            credentialEnvironmentNames: ["GEMINI_API_KEY", "GOOGLE_API_KEY"]
        ),
        "kimi": ProviderContractSpec(
            id: "kimi", title: "Kimi / Moonshot", detail: "Connect a Moonshot API key. Use Custom for endpoints with a different compatibility contract.",
            defaultModel: "kimi-k3", authMode: "api",
            profileAuthMode: "api", runtimeRoute: "jarvis-moonshot-api",
            probeRoute: "jarvis-moonshot-api", probeProfileID: nil,
            defaultBaseURL: "https://api.moonshot.ai/v1", baseURLRequired: false,
            conversationModel: nil,
            openAIRuntime: "openclaw", anthropicRuntime: "openclaw",
            credentialEnvironmentNames: ["MOONSHOT_API_KEY"]
        ),
        "deepseek": ProviderContractSpec(
            id: "deepseek", title: "DeepSeek", detail: "Connect a DeepSeek API key through its OpenAI-compatible interface.",
            defaultModel: "deepseek-v4-pro", authMode: "api",
            profileAuthMode: "api", runtimeRoute: "jarvis-compatible",
            probeRoute: "jarvis-compatible", probeProfileID: nil,
            defaultBaseURL: "https://api.deepseek.com", baseURLRequired: false,
            conversationModel: nil,
            openAIRuntime: "openclaw", anthropicRuntime: "openclaw",
            credentialEnvironmentNames: ["DEEPSEEK_API_KEY"]
        ),
        "custom": ProviderContractSpec(
            id: "custom", title: "Custom compatible API", detail: "Use an OpenAI-compatible API with an HTTPS base URL and provider-supplied model ID.",
            defaultModel: "", authMode: "api",
            profileAuthMode: "api", runtimeRoute: "jarvis-compatible",
            probeRoute: "jarvis-compatible", probeProfileID: nil,
            defaultBaseURL: "", baseURLRequired: true,
            conversationModel: nil,
            openAIRuntime: "openclaw", anthropicRuntime: "openclaw",
            credentialEnvironmentNames: []
        ),
    ]

    static let connectionFailures: [String: ConnectionFailureContractSpec] = [
        "AUTH_REJECTED": ConnectionFailureContractSpec(
            code: "AUTH_REJECTED", retryable: false,
            reconnectRequired: true,
            messageEnglish: "The provider rejected this credential. Reconnect the model in Settings.", messageChinese: "模型服务商拒绝了当前凭证，请在设置中重新连接。",
            shortEnglish: "credential rejected", shortChinese: "凭证被拒绝"
        ),
        "MODEL_UNAVAILABLE": ConnectionFailureContractSpec(
            code: "MODEL_UNAVAILABLE", retryable: false,
            reconnectRequired: true,
            messageEnglish: "The selected model is unavailable for this account. Choose another model in Settings.", messageChinese: "当前账号无法使用所选模型，请重新选择并连接。",
            shortEnglish: "model unavailable", shortChinese: "模型不可用"
        ),
        "RATE_LIMITED": ConnectionFailureContractSpec(
            code: "RATE_LIMITED", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The provider is rate-limiting requests. Your connection was kept.", messageChinese: "服务商正在限流，连接已保留，请稍后再试。",
            shortEnglish: "provider rate-limited", shortChinese: "服务商限流"
        ),
        "PROVIDER_UNAVAILABLE": ConnectionFailureContractSpec(
            code: "PROVIDER_UNAVAILABLE", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The provider is temporarily unavailable. Your connection was kept.", messageChinese: "服务商暂时不可用，连接已保留，请稍后再试。",
            shortEnglish: "provider unavailable", shortChinese: "服务商不可用"
        ),
        "PROVIDER_TIMEOUT": ConnectionFailureContractSpec(
            code: "PROVIDER_TIMEOUT", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The provider timed out. Your connection was kept.", messageChinese: "服务商响应超时，连接已保留，请再试一次。",
            shortEnglish: "provider timed out", shortChinese: "服务商超时"
        ),
        "PROBE_TIMEOUT": ConnectionFailureContractSpec(
            code: "PROBE_TIMEOUT", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The provider did not answer the connection check in time.", messageChinese: "服务商未能及时完成连接验证。",
            shortEnglish: "verification timed out", shortChinese: "验证超时"
        ),
        "ENDPOINT_UNREACHABLE": ConnectionFailureContractSpec(
            code: "ENDPOINT_UNREACHABLE", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The provider endpoint is temporarily unreachable. Your connection was kept.", messageChinese: "暂时无法安全访问服务商接口，连接已保留。",
            shortEnglish: "endpoint unreachable", shortChinese: "接口不可达"
        ),
        "PROVIDER_FAILED": ConnectionFailureContractSpec(
            code: "PROVIDER_FAILED", retryable: false,
            reconnectRequired: false,
            messageEnglish: "The provider could not complete this request. The connection was left unchanged.", messageChinese: "服务商未能完成这个请求，当前连接设置没有改变。",
            shortEnglish: "request failed", shortChinese: "请求失败"
        ),
        "LOCAL_GATEWAY_UNREACHABLE": ConnectionFailureContractSpec(
            code: "LOCAL_GATEWAY_UNREACHABLE", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The local model gateway disconnected. The connection setting was kept and will recover automatically.", messageChinese: "本地模型网关刚刚断开，连接设置未改变；下次请求会自动恢复。",
            shortEnglish: "local gateway unavailable", shortChinese: "本地网关不可用"
        ),
        "INVALID_PROBE_OUTPUT": ConnectionFailureContractSpec(
            code: "INVALID_PROBE_OUTPUT", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The provider check returned an unreadable response.", messageChinese: "服务商返回了无法读取的验证结果。",
            shortEnglish: "invalid verification response", shortChinese: "验证结果无效"
        ),
        "PROVIDER_NOT_PROBED": ConnectionFailureContractSpec(
            code: "PROVIDER_NOT_PROBED", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The selected provider was not reached by the connection check.", messageChinese: "连接验证未能访问所选服务商。",
            shortEnglish: "provider not reached", shortChinese: "未访问服务商"
        ),
        "PROFILE_NOT_PROBED": ConnectionFailureContractSpec(
            code: "PROFILE_NOT_PROBED", retryable: false,
            reconnectRequired: true,
            messageEnglish: "A different saved account answered the check. Reconnect this MERRICK account.", messageChinese: "验证命中了另一已保存账号，请重新连接当前 MERRICK 账号。",
            shortEnglish: "different account verified", shortChinese: "验证账号不一致"
        ),
        "PROBE_FAILED": ConnectionFailureContractSpec(
            code: "PROBE_FAILED", retryable: true,
            reconnectRequired: false,
            messageEnglish: "The provider could not complete the connection check.", messageChinese: "服务商未能完成连接验证。",
            shortEnglish: "verification failed", shortChinese: "验证失败"
        ),
        "VALIDATION_REQUIRED": ConnectionFailureContractSpec(
            code: "VALIDATION_REQUIRED", retryable: false,
            reconnectRequired: true,
            messageEnglish: "This saved connection must be verified before it can be used.", messageChinese: "此已保存连接需要验证后才能使用。",
            shortEnglish: "verification required", shortChinese: "需要验证"
        ),
        "NOT_CONFIGURED": ConnectionFailureContractSpec(
            code: "NOT_CONFIGURED", retryable: false,
            reconnectRequired: true,
            messageEnglish: "No model provider has been configured.", messageChinese: "尚未配置模型服务商。",
            shortEnglish: "not configured", shortChinese: "未配置"
        ),
        "READY": ConnectionFailureContractSpec(
            code: "READY", retryable: false,
            reconnectRequired: false,
            messageEnglish: "Connection verified.", messageChinese: "连接验证成功。",
            shortEnglish: "ready", shortChinese: "已就绪"
        ),
    ]

    static let failureMatchers: [FailureMatcherContractSpec] = [
        FailureMatcherContractSpec(runtimeCode: "MODEL_UNAVAILABLE", probeCode: "MODEL_UNAVAILABLE", pattern: "unknown model|model_not_found|model.{0,80}(?:404|not found)"),
        FailureMatcherContractSpec(runtimeCode: "AUTH_REJECTED", probeCode: "AUTH_REJECTED", pattern: "(?:^|[^0-9])(?:401|403)(?:[^0-9]|$)|unauthor|forbidden|invalid authentication|invalid api key|invalid_api_key|token has expired|oauth token expired|not logged in|login required"),
        FailureMatcherContractSpec(runtimeCode: "RATE_LIMITED", probeCode: "RATE_LIMITED", pattern: "(?:^|[^0-9])429(?:[^0-9]|$)|rate limit|quota"),
        FailureMatcherContractSpec(runtimeCode: "PROVIDER_UNAVAILABLE", probeCode: "PROVIDER_UNAVAILABLE", pattern: "(?:^|[^0-9])(?:500|502|503|504)(?:[^0-9]|$)|service unavailable|bad gateway|upstream unavailable|overloaded"),
        FailureMatcherContractSpec(runtimeCode: "PROVIDER_TIMEOUT", probeCode: "PROBE_TIMEOUT", pattern: "timeout|timed out"),
        FailureMatcherContractSpec(runtimeCode: "ENDPOINT_UNREACHABLE", probeCode: "ENDPOINT_UNREACHABLE", pattern: "connection failure|connection failed|connect error|\\bdns\\b|\\btls\\b|certificate|network"),
    ]

    static let defaultProvider = providers["codex"]!
}
